kind: pipeline
name: deploy-on-minikube

steps:
- name: Build and Publish Image to Docker Registry
  image: plugins/docker
  settings:
    username: 
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: chaturvedisulabh/golang-restful-json-api
    dockerfile: ./Dockerfile
    
- name: Deploy to kubernetes cluster
  image: vallard/drone-kube
  settings:
    template: kubernetes/manifests/deployment.yml
    namespace: default
    server:
      from_secret: KUBE_SERVER
    token:
      from_secret: KUBE_TOKEN
    ca:
      from_secret: KUBE_CA
