kind: pipeline
name: build-image-publish-to-docker-registry-and-deploy-on-kubernetes-cluster

steps:
- name: Build and Publish Image to Docker Registry
  image: plugins/docker
  settings:
    username: 
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: chaturvedisulabh/golang-restful-json-api
    dockerfile: ./Dockerfile
