kind: pipeline
name: deploy-on-minikube

steps:
- name: Build and Publish Image to Docker Registry
  image: plugins/docker
  settings:
    username: 
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: 
      from_secret: GIT_REPO
    dockerfile: ./Dockerfile
